name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Checkout
      uses: actions/checkout@v3 
        
    - name: Test
      run: go build -v ./...
      
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 

    - name: Build
      run: go build -v ./...
      
  buildDocker:
    name: Build Docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
      
    - name: build image from dockerfile
      run: docker build -t diesi/demo:latest .
      
    - name: Trivy Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'diesi/demo:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Commmit hash variable
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: diesi/demo:latest, diesi/demo:${{ steps.vars.outputs.sha_short }}
